# @package _global_
defaults:
  - /runner/default

runner:
  # checkpointing_steps: 5000
  # validation_steps: 2500
  # checkpointing_steps: 10000
  checkpointing_steps: 100

  validation_steps: 1000000
  lr_scheduler: constant_with_warmup
  enable_xformers_memory_efficient_attention: true
