defaults:
  - config
  - _self_

log_root_prefix: ./magicdrive-log/test

runner:
  # validation_batch_size: 4
  validation_batch_size: 1

resume_on_exists: false
show_box: true

fix_seed_for_every_generation: False
